### Converting a list into a 3x3 numpy array

In [23]:
import numpy as np
import pandas as pd

In [24]:
list = [0,1,2,3,4,5,6,7,8]

In [25]:
mat_3x3 = np.array(list).reshape(3,3)
mat_flat = np.array(list)

In [26]:
print(mat_3x3)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


### Output the mean, variance, standard deviation, max, min, and sum of the rows, columns, and elements in a 3 x 3 matrix.

In [27]:
mat_3x3[:, 0].mean()

3.0

In [28]:
mat_3x3[:, 1].mean()

4.0

In [29]:
mat_3x3[:, -1].mean()

5.0

### Use a for loop to automate mean calculation across axis (The 3 above cells)

In [39]:
mat_3x3_rows = mat_3x3.shape[0]
mat_3x3_cols = mat_3x3.shape[1]

axis1_mean = []  #column
axis2_mean = []  #row
flattened_mean = []  #flat

for i in range(mat_3x3_rows):                  # mean of columns of 3x3 matrix
    axis1_mean.append(mat_3x3[:, i].mean())

for i in range(mat_3x3_cols):                  # mean of rows of 3x3 matrix
    axis2_mean.append(mat_3x3[i, :].mean())
    
flattened_mean = mat_flat.mean()               # mean of initial flattened matrix
    
    
print(axis1_mean)
print(axis2_mean)
print(flattened_mean)

[3.0, 4.0, 5.0]
[1.0, 4.0, 7.0]
4.0


### Now it's Variance

In [35]:
axis1_var = []
axis2_var = []
flattened_var = []

for i in range(mat_3x3_cols):               #variance for each column
    axis1_var.append(mat_3x3[:, i].var())
    
for i in range(mat_3x3_rows):               #variance for each row
    axis2_var.append(mat_3x3[i, :].var())
    
flattened_var = mat_flat.var()

print(axis1_var)
print(axis2_var)
print(flattened_variance)

[6.0, 6.0, 6.0]
[0.6666666666666666, 0.6666666666666666, 0.6666666666666666]
6.666666666666667


### Standard Deviation

In [41]:
axis1_std = []
axis2_std = []
flattened_std = []

for i in range(mat_3x3_cols):
    axis1_std.append(mat_3x3[:, i].std())
    
for i in range(mat_3x3_rows):
    axis2_std.append(mat_3x3[i, :].std())
    
flattened_std = mat_flat.std()    
    
print(axis1_std)
print(axis2_std)
print(flattened_std)

[2.449489742783178, 2.449489742783178, 2.449489742783178]
[0.816496580927726, 0.816496580927726, 0.816496580927726]
2.581988897471611


### Max

In [43]:
axis1_max = []
axis2_max = []
flattened_max = []

for i in range(mat_3x3_cols):
    axis1_max.append(mat_3x3[:, i].max())
    
for i in range(mat_3x3_rows):
    axis2_max.append(mat_3x3[i, :].max())
    
flattened_max = mat_flat.max()

print(axis1_max)
print(axis2_max)
print(flattened_max)

[6, 7, 8]
[2, 5, 8]
8


### Min

In [45]:
axis1_min = []
axis2_min = []
flattened_min = []

for i in range(mat_3x3_cols):
    axis1_min.append(mat_3x3[:, i].min())
    
for i in range(mat_3x3_rows):
    axis2_min.append(mat_3x3[i, :].min())
    
flattened_min = mat_flat.min()

print(axis1_min)
print(axis2_min)
print(flattened_min)

[0, 1, 2]
[0, 3, 6]
0


### Sum

In [46]:
axis1_sum = []
axis2_sum = []
flattened_sum = []

for i in range(mat_3x3_cols):
    axis1_sum.append(mat_3x3[:, i].sum())
    
for i in range(mat_3x3_rows):
    axis2_sum.append(mat_3x3[i, :].sum())
    
flattened_sum = mat_flat.sum()

print(axis1_sum)
print(axis2_sum)
print(flattened_sum)

[9, 12, 15]
[3, 12, 21]
36
